version: '2'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    networks:
      - net

  redis:
    image: redis:3.2-alpine
    networks:
      - net

  apache:
    build: ./docker-images/apache-php
    volumes:
      - "./www/:/var/www/html/"
    ports:
      - "81:80"
    environment:
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
    networks:
      - net

  varnish:
    image: million12/varnish
    ports:
      - "80:80"
    volumes:
      - "./volumes/varnish/etc/varnish/default.vcl:/etc/varnish/default.vcl"
    networks:
      - net

networks:
  net:
    driver: bridge

