version: '2'

services:
  apache:
    build: ./docker-images/apache-php
    volumes:
      - "./www:/var/www/html/"
    ports:
      - "80:80"
    environment:
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
